In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a1d= np.array([1,2,3,4,5])
a1d

array([1, 2, 3, 4, 5])

In [6]:
a2d=np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
)

In [7]:
a3d=np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
           ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]
    ]
)

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
a=np.zeros((4,2))
a


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [13]:
a.ndim

2

In [14]:
b.ndim

1

In [15]:
n=np.ones((3,4))
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
n*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [17]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [18]:
np.empty((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c.strides

(24, 8)

In [21]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [23]:
data=np.array([1,2])
data

array([1, 2])

In [24]:
ones=np.array([2,3])
ones

array([2, 3])

In [25]:
data+ones

array([3, 5])

In [26]:
data-ones

array([-1, -1])

In [27]:
data*ones

array([2, 6])

In [28]:
data/ones

array([0.5       , 0.66666667])

In [29]:
ones/data

array([2. , 1.5])

In [30]:
data.shape

(2,)

In [31]:
ones.shape

(2,)

In [32]:
ones.min()
ones.max()

np.int64(3)

In [33]:
d=np.array([
   [[9,8] ,[2,3] ],
  [ [9,5], [4,5] ],
   [ [6,7], [7,4] ]
])

In [34]:
d.min()

np.int64(2)

In [35]:
d.ndim

3

In [36]:
d.min()

np.int64(2)

In [37]:
d.max()

np.int64(9)

In [38]:
d.max(axis=1)

array([[9, 8],
       [9, 5],
       [7, 7]])

In [39]:
f=np.array([
    [3,4],
    [6,7],
    [9,3]
])

In [40]:
f.max(axis=1)


array([4, 7, 9])

In [41]:
a2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [42]:
a2[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
a2[::2,::3]

array([[ 1,  4],
       [ 9, 12]])

In [44]:
a2[[0,2]][:,[0,2]]

array([[ 1,  3],
       [ 9, 11]])

In [45]:
a2[[0,0,2,2],[0,2,0,2]]

array([ 1,  3,  9, 11])

In [46]:
a2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [47]:
a2[0,0]=10

In [48]:
a2

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])