In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
type(a)

numpy.ndarray

In [7]:
a1d= np.array([1,2,3,4,5])
a1d

array([1, 2, 3, 4, 5])

In [8]:
a2d=np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
)

In [ ]:
a3d=np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
           ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]
    ]
)

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
a=np.zeros((4,2))
a


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [26]:
a.ndim

2

In [29]:
b.ndim

1

In [31]:
n=np.ones((3,4))
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
n*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [34]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [37]:
np.empty((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
c.strides

(24, 8)

In [42]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [53]:
data=np.array([1,2])
data

array([1, 2])

In [54]:
ones=np.array([2,3])
ones

array([2, 3])

In [55]:
data+ones

array([3, 5])

In [56]:
data-ones

array([-1, -1])

In [57]:
data*ones

array([2, 6])

In [49]:
data/ones

array([0.5, 1. ])

In [50]:
ones/data

array([2., 1.])

In [58]:
data.shape

(2,)

In [59]:
ones.shape

(2,)

In [62]:
ones.min()
ones.max()

np.int64(3)

In [67]:
d=np.array([
   [[9,8] ,[2,3] ],
  [ [9,5], [4,5] ],
   [ [6,7], [7,4] ]
])

In [66]:
d.min()

np.int64(2)

In [69]:
d.ndim

3

In [70]:
d.min()

np.int64(2)

In [71]:
d.max()

np.int64(9)

In [72]:
d.max(axis=1)

array([[9, 8],
       [9, 5],
       [7, 7]])

In [78]:
f=np.array([
    [3,4],
    [6,7],
    [9,3]
])

In [80]:
f.max(axis=1)


array([4, 7, 9])